-- Shared starter library. user_id is null so every account can read these.

insert into public.exercises (user_id, name, muscle_group, equipment) values
  -- glutes
  (null, 'Hip Thrust',                    'Glutes',      'Barbell'),
  (null, 'Smith Machine Hip Thrust',      'Glutes',      'Machine'),
  (null, 'Single-Leg Hip Thrust',         'Glutes',      'Bodyweight'),
  (null, 'Glute Bridge',                  'Glutes',      'Barbell'),
  (null, 'Cable Kickback',                'Glutes',      'Cable'),
  (null, 'Cable Glute Abduction',         'Glutes',      'Cable'),
  (null, 'Hip Abduction Machine',         'Glutes',      'Machine'),
  (null, 'Reverse Hyperextension',        'Glutes',      'Machine'),
  (null, 'Step-Up',                       'Glutes',      'Dumbbell'),
  (null, 'Curtsy Lunge',                  'Glutes',      'Dumbbell'),
  (null, 'Bulgarian Split Squat',         'Glutes',      'Dumbbell'),
  (null, 'Sumo Deadlift',                 'Glutes',      'Barbell'),
  (null, 'Kas Glute Bridge',              'Glutes',      'Barbell'),
  -- quads
  (null, 'Back Squat',                    'Quads',       'Barbell'),
  (null, 'Front Squat',                   'Quads',       'Barbell'),
  (null, 'Hack Squat',                    'Quads',       'Machine'),
  (null, 'Leg Press',                     'Quads',       'Machine'),
  (null, 'Leg Extension',                 'Quads',       'Machine'),
  (null, 'Goblet Squat',                  'Quads',       'Dumbbell'),
  (null, 'Walking Lunge',                 'Quads',       'Dumbbell'),
  (null, 'Smith Machine Squat',           'Quads',       'Machine'),
  (null, 'Pendulum Squat',                'Quads',       'Machine'),
  -- hamstrings
  (null, 'Romanian Deadlift',             'Hamstrings',  'Barbell'),
  (null, 'Dumbbell Romanian Deadlift',    'Hamstrings',  'Dumbbell'),
  (null, 'Seated Leg Curl',               'Hamstrings',  'Machine'),
  (null, 'Lying Leg Curl',                'Hamstrings',  'Machine'),
  (null, 'Nordic Curl',                   'Hamstrings',  'Bodyweight'),
  (null, 'Good Morning',                  'Hamstrings',  'Barbell'),
  (null, 'Cable Pull-Through',            'Hamstrings',  'Cable'),
  (null, 'Conventional Deadlift',         'Hamstrings',  'Barbell'),
  -- calves
  (null, 'Standing Calf Raise',           'Calves',      'Machine'),
  (null, 'Seated Calf Raise',             'Calves',      'Machine'),
  (null, 'Leg Press Calf Raise',          'Calves',      'Machine'),
  -- back
  (null, 'Lat Pulldown',                  'Back',        'Cable'),
  (null, 'Wide-Grip Lat Pulldown',        'Back',        'Cable'),
  (null, 'Neutral-Grip Lat Pulldown',     'Back',        'Cable'),
  (null, 'Assisted Pull-Up',              'Back',        'Machine'),
  (null, 'Pull-Up',                       'Back',        'Bodyweight'),
  (null, 'Chest-Supported Row',           'Back',        'Machine'),
  (null, 'Seated Cable Row',              'Back',        'Cable'),
  (null, 'Barbell Row',                   'Back',        'Barbell'),
  (null, 'Single-Arm Dumbbell Row',       'Back',        'Dumbbell'),
  (null, 'T-Bar Row',                     'Back',        'Barbell'),
  (null, 'Straight-Arm Pulldown',         'Back',        'Cable'),
  (null, 'Face Pull',                     'Back',        'Cable'),
  -- chest
  (null, 'Barbell Bench Press',           'Chest',       'Barbell'),
  (null, 'Incline Barbell Bench Press',   'Chest',       'Barbell'),
  (null, 'Dumbbell Bench Press',          'Chest',       'Dumbbell'),
  (null, 'Incline Dumbbell Press',        'Chest',       'Dumbbell'),
  (null, 'Machine Chest Press',           'Chest',       'Machine'),
  (null, 'Pec Deck',                      'Chest',       'Machine'),
  (null, 'Cable Fly',                     'Chest',       'Cable'),
  (null, 'Push-Up',                       'Chest',       'Bodyweight'),
  (null, 'Dip',                           'Chest',       'Bodyweight'),
  -- shoulders
  (null, 'Overhead Press',                'Shoulders',   'Barbell'),
  (null, 'Seated Dumbbell Shoulder Press','Shoulders',   'Dumbbell'),
  (null, 'Machine Shoulder Press',        'Shoulders',   'Machine'),
  (null, 'Lateral Raise',                 'Shoulders',   'Dumbbell'),
  (null, 'Cable Lateral Raise',           'Shoulders',   'Cable'),
  (null, 'Rear Delt Fly',                 'Shoulders',   'Dumbbell'),
  (null, 'Reverse Pec Deck',              'Shoulders',   'Machine'),
  (null, 'Upright Row',                   'Shoulders',   'Cable'),
  (null, 'Front Raise',                   'Shoulders',   'Dumbbell'),
  -- biceps
  (null, 'Dumbbell Curl',                 'Biceps',      'Dumbbell'),
  (null, 'Barbell Curl',                  'Biceps',      'Barbell'),
  (null, 'EZ-Bar Curl',                   'Biceps',      'Barbell'),
  (null, 'Incline Dumbbell Curl',         'Biceps',      'Dumbbell'),
  (null, 'Hammer Curl',                   'Biceps',      'Dumbbell'),
  (null, 'Cable Curl',                    'Biceps',      'Cable'),
  (null, 'Preacher Curl',                 'Biceps',      'Machine'),
  -- triceps
  (null, 'Triceps Pushdown',              'Triceps',     'Cable'),
  (null, 'Rope Pushdown',                 'Triceps',     'Cable'),
  (null, 'Overhead Cable Extension',      'Triceps',     'Cable'),
  (null, 'Skull Crusher',                 'Triceps',     'Barbell'),
  (null, 'Close-Grip Bench Press',        'Triceps',     'Barbell'),
  (null, 'Dumbbell Kickback',             'Triceps',     'Dumbbell'),
  -- core
  (null, 'Cable Crunch',                  'Core',        'Cable'),
  (null, 'Hanging Leg Raise',             'Core',        'Bodyweight'),
  (null, 'Plank',                         'Core',        'Bodyweight'),
  (null, 'Ab Wheel Rollout',              'Core',        'Other'),
  (null, 'Russian Twist',                 'Core',        'Dumbbell'),
  (null, 'Dead Bug',                      'Core',        'Bodyweight'),
  (null, 'Pallof Press',                  'Core',        'Cable'),
  -- conditioning
  (null, 'Treadmill Incline Walk',        'Conditioning','Machine'),
  (null, 'Stairmaster',                   'Conditioning','Machine'),
  (null, 'Assault Bike',                  'Conditioning','Machine'),
  (null, 'Rowing Machine',                'Conditioning','Machine'),
  (null, 'Easy Run',                      'Conditioning','Bodyweight')
on conflict do nothing;
